ethereumNodeURL: "http://localhost:7545"
privateKey: "2b955afcaa3a6e5747c02c1f3c5a6ed1295cc351415cbd14affcf73ee979dee8"
DataCollectionContractAddress: "0x546449Ee684DbaB4532Aeb6603E128eB29387466"
DataCollectionabi: >
  [
    {
      "constant": false,
      "inputs": [
        {
          "name": "_deviceId",
          "type": "uint256"
        },
        {
          "name": "_timestamp",
          "type": "uint256"
        },
        {
          "name": "_value",
          "type": "uint256"
        }
      ],
      "name": "addData",
      "outputs": [],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "deviceId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "timestamp",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "value",
          "type": "uint256"
        }
      ],
      "name": "DataAdded",
      "type": "event"
    }
  ]

