database:
  username: root
  password: root
  host: localhost
  port: 3306
  dbname: DataCollection
ethereumNodeURL: "ws://localhost:7545"
privateKey: "7da30821020c8ffd00d07e175dc372c66f86063de09774b34b7ba170783c3276"
DataCollectionContractAddress: "0xe19da45285ab880d0ab80ec48047adaf144a2094"
DataCollectionabi: >
 [
  {
    "constant": false,
    "inputs": [
      {
        "name": "_deviceId",
        "type": "int64"
      },
      {
        "name": "_dataHash",
        "type": "bytes32"
      }
    ],
    "name": "recordDataHash",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "_deviceId",
        "type": "int64"
      },
      {
        "name": "_temperature",
        "type": "int64"
      },
      {
        "name": "_unit",
        "type": "string"
      },
      {
        "name": "_timestamp",
        "type": "string"
      }
    ],
    "name": "recordTemperature",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "deviceId",
        "type": "int64"
      },
      {
        "indexed": false,
        "name": "temperature",
        "type": "int64"
      },
      {
        "indexed": false,
        "name": "unit",
        "type": "string"
      },
      {
        "indexed": false,
        "name": "timestamp",
        "type": "string"
      }
    ],
    "name": "TemperatureRecorded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "name": "deviceId",
        "type": "int64"
      },
      {
        "indexed": false,
        "name": "dataHash",
        "type": "bytes32"
      }
    ],
    "name": "DataHashRecorded",
    "type": "event"
  }
 ]
